server:
  port: 8100

spring:
    application:
      name: xupt-acat-user-service
    cloud:
    #  alibaba:
    #    seata:
    #    #自定义事务组名称需要与seata-server中的对应
    #      tx-service-group: fsp_tx_group
      nacos:
        discovery:
          server-addr: localhost:8848

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/recruitment?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: interview
            password: acat
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
    main:
            allow-bean-definition-overriding: true
    ## Redis 配置
    redis:
      ## Redis数据库索引（默认为0）
      database: 0
      ## Redis服务器地址
      host: localhost
      ## Redis服务器连接端口
      port: 6379
      ## Redis服务器连接密码（默认为空）
      password:
      jedis:
        pool:
          ## 连接池最大连接数（使用负值表示没有限制）
          #spring.redis.pool.max-active=8
          max-active: 8
          ## 连接池最大阻塞等待时间（使用负值表示没有限制）
          #spring.redis.pool.max-wait=-1
          max-wait: -1
          ## 连接池中的最大空闲连接
          #spring.redis.pool.max-idle=8
          max-idle: 8
          ## 连接池中的最小空闲连接
          #spring.redis.pool.min-idle=0
          min-idle: 0
      ## 连接超时时间（毫秒）
      timeout: 1200

    #将themilef的默认缓存禁用，热加载生效
    thymeleaf:
      cache: false

feign:
  hystrix:
    enabled: false

#mybatis
mybatis-plus:
  #mapper-locations: classpath*:/mapper/*.xml
  global-config:
      #数据库相关配置
      db-config:
        #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
        id-type: AUTO


rsa:
  key:
    pubKeyFile: /root/xupt-acat-recruitment/xupt-acat-recruitment-parent/auth_key/id_key_rsa.pub