server:
  port: 9200
spring:
    application:
      name: profess-artifact-note-service
    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848

feign:
  hystrix:
    enabled: false

rsa:
  key:
    pubKeyFile: D:\WorkSpace\profess-artifact-parentt\resources\id_key_rsa.pub