server:
  port: 9527

spring:
    application:
      name: profess-artifact-user-gateway
    cloud:
      #alibaba:
      #  seata:
      #    #自定义事务组名称需要与seata-server中的对应
      #    tx-service-group: fsp_tx_group
      nacos:
        discovery:
          server-addr: localhost:8848
      gateway:
        discovery:
          locator:
            enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
        routes:

          - id: user_service_route #use_service_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
            #uri: http://localhost:8001          #匹配后提供服务的路由地址
            uri: lb://profess-artifact-user-service #匹配后提供服务的路由地址
            predicates:
              - Path=/user-service/**         # 断言，路径相匹配的进行路由
              #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
              #- Cookie=username,zzyy
              #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

          - id: chat_service_route #interview_service_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
            #uri: http://localhost:8001          #匹配后提供服务的路由地址
            uri: lb:ws://profess-artifact-chat-service #匹配后提供服务的路由地址
            predicates:
              - Path=/chat-service/**         # 断言，路径相匹配的进行路由
              #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
              #- Cookie=username,zzyy
              #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

          - id: oss_service_route #use_service_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
            #uri: http://localhost:8001          #匹配后提供服务的路由地址
            uri: lb://profess-artifact-oss-service #匹配后提供服务的路由地址
            predicates:
              - Path=/oss-service/**         # 断言，路径相匹配的进行路由
              #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
              #- Cookie=username,zzyy
              #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
